version: '3.9'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jesus
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  weather-app:
    build:
      context: ./weather-app
    container_name: weather-app
    ports:
      - 8080:8080

  weather-front:
    build:
      context: ./weather-front
    container_name: weather-front
    ports:
      - 4200:80

volumes:
  postgres-data: