name: Build and Test Java Spring Boot Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd weather-app
        mvn clean install -DskipTests
    - name: Start Application
      run: |
        cd weather-app
        mvn spring-boot:run &
        sleep 15 # Give the application some time to start
    - name: Run Tests
      run: |
        cd weather-app
        mvn test
    - name: Test Report
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
          name: SpringBoot Report
          path: target/site/jacoco/
    - name: Stop Application
      run: |
        cd weather-app
        pkill -f "weather-app.jar"
