name: Java Spring Boot Application CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: |
          cd weather-app
          mvn -B package -Pcoverage
 
    - name: Generate JaCoCo badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true
        generate-summary: true
            
    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: JaCoCo Report
          path: weather-app/htmlReport/