name: Spring Boot CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Spring Boot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
            cd weather-app
            mvn clean install -DskipTests

      - name: Run tests
        run: |
            cd weather-app
            mvn test
