name: Build and Test Java Spring Boot Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        cd weather-app
        mvn clean install

    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: Jacoco Report
          path: weather-app/target/site/jacoco/